LoopKit/LoopKit

.travis.yml
CarbKit/CarbStore.swift
CarbKit/UI/CarbEntryTableViewController.swift
LoopKit/DailyValueSchedule.swift

Refactoring CarbStore notification conditions

---

CarbKit/Info.plist
CarbKit/UI/CarbEntryEditViewController.swift
GlucoseKit/Info.plist
InsulinKit/Info.plist
LoopKit/Info.plist
LoopKit/UI/DailyValueScheduleTableViewController.swift
LoopKit/UI/UIViewController.swift

Also, auto-enabling the keyboard when entering carbs

Error and timezone display improvements

---

InsulinKit/DoseStore.swift

This will allow clients to quickly identify changes in value thresholds and send notifications.

Return the last-saved reservoir value when adding a new one.

---

GlucoseKit/GlucoseStore.swift
LoopKit.xcodeproj/project.pbxproj

Method to add multiple glucose values at once (for backfill purposes)

---

CarbKit/UI/CarbKit.storyboard
InsulinKit/UI/Base.lproj/InsulinKit.storyboard

Decrease the size of the entries table header text

---

GlucoseKit/GlucoseMath.swift
GlucoseKit/GlucoseSampleValue.swift
GlucoseKit/GlucoseStore.swift
GlucoseKit/HKQuantitySample.swift
GlucoseKitTests/GlucoseMathTests.swift
InsulinKit/DoseEntry.swift
InsulinKit/DoseStore.swift
InsulinKit/PersistenceController.swift
InsulinKit/PumpEvent.swift
InsulinKit/UI/Base.lproj/InsulinKit.storyboard
InsulinKit/UI/InsulinDeliveryTableViewController.swift
InsulinKit/UI/ReservoirTableViewController.swift
LoopKit Example/Base.lproj/Main.storyboard
LoopKit Example/Extensions/InsulinDeliveryTableViewController.swift
LoopKit Example/Extensions/NSUserDefaults.swift
LoopKit Example/MasterViewController.swift
LoopKit.xcodeproj/project.pbxproj

Adding upload delegation to DoseStore

---

InsulinKit/DoseStore.swift
InsulinKit/UI/InsulinDeliveryTableViewController.swift

Display the stored title in the history table and clarify the since date

---

InsulinKit/DoseStore.swift
InsulinKit/Model.xcdatamodeld/Model.xcdatamodel/contents
InsulinKit/PersistedPumpEvent.swift
InsulinKit/PumpEvent+CoreDataProperties.swift

Removing deviceID from the PumpEvent model

---

InsulinKit/InsulinMath.swift
InsulinKitTests/Fixtures/reconcile_history_output.json
LoopKitTests/LoopMathTests.swift

Fixes https://github.com/loudnate/Loop/issues/138

Drop 0-min temp basal cancellations during the reconcile pass

---

CarbKit/CarbStore.swift
GlucoseKit/GlucoseStore.swift
InsulinKit/DoseStore.swift
LICENSE
LoopKit Example/MasterViewController.swift
LoopKit.xcodeproj/project.pbxproj
LoopKit/DailyValueSchedule.swift
LoopKit/UI/CommandResponseViewController.swift
LoopKit/UI/TextFieldTableViewController.swift

And allowing TextFieldTableViewController to be overridden.

Diagnostic reporting

---

CarbKit/Info.plist
CarbKitTests/Info.plist
GlucoseKit/Info.plist
GlucoseKitTests/Info.plist
InsulinKit/Info.plist
InsulinKitTests/Info.plist
LoopKit Example/Info.plist
LoopKit ExampleUITests/Info.plist
LoopKit.xcodeproj/project.pbxproj
LoopKit/DailyValueSchedule.swift
LoopKit/Info.plist
LoopKit/TimeZone.swift
LoopKit/UI/DailyValueScheduleTableViewController.swift
LoopKitTests/Info.plist

* Ensuring only fixed-offset time zones are used
* Version bump

Version 1.0.1

---

CarbKit/CarbEntry.swift
CarbKit/CarbStore.swift
CarbKit/HKQuantitySample.swift
CarbKit/StoredCarbEntry.swift
CarbKit/UI/CarbEntryTableViewController.swift
CarbKit/UI/NewCarbEntry.swift
LoopKit Example/Managers/DeviceDataManager.swift

Reverts LoopKit/LoopKit#79.  Accidentally merged to master.  Should have been dev.

Revert "Add callback for carb entries needing upload"

---

CarbKit/UI/CarbEntryEditViewController.swift
CarbKit/UI/CarbEntryValidationNavigationDelegate.swift
CarbKit/UI/CarbKit.storyboard
CarbKit/UI/DecimalTextFieldTableViewCell.swift
CarbKitTests/UI/CarbEntryEditViewControllerTests.swift
LoopKit Example/Base.lproj/Main.storyboard
LoopKit.xcodeproj/project.pbxproj

Don't allow absorption time entries over 999. Basic validation from the Carb Entry Edit VC.
https://github.com/LoopKit/Loop/issues/312
@ps2

Add validation for Carb Entry Absorption time (less than 999)

---

CarbKit/UI/CarbKit.storyboard

Removed a hanging segue @loudnate @ps2

clean up storyboard warnings

---

CarbKit/CarbStore.swift
CarbKit/UI/AbsorptionTimeTextFieldTableViewCell.swift
CarbKit/UI/CarbEntryEditViewController.swift
CarbKit/UI/CarbEntryTableViewController.swift
InsulinKit/DoseStore.swift
InsulinKit/InsulinMath.swift
InsulinKit/PersistenceController.swift
InsulinKit/PumpEvent.swift
InsulinKit/Reservoir.swift
LoopKit Example/Extensions/NSUserDefaults.swift
LoopKit/Double.swift
LoopKit/GlucoseRangeSchedule.swift
LoopKit/LoopMath.swift

remove unnecessary 'as' conditions that were added from the Xcode migrator

remove unnecessary 'as' conditions

---

GlucoseKit/GlucoseStore.swift

Currently the glucose sample cache can balloon in size when using the app's UI, and it wouldn't be pruned until the next glucose entry was added.
This keeps the cache up-to-date in the same ways as before, but always runs the date filter immediately after updating.

Keep glucose sample data cache more tightly pruned

---

CarbKit/CarbStore.swift
CarbKit/UI/CarbEntryEditViewController.swift
CarbKit/UI/CarbKit.storyboard
CarbKit/UI/DatePickerTableViewCell.swift
CarbKit/UI/DatePickerTableViewCell.xib
LoopKit.xcodeproj/project.pbxproj

* Allows DatePickerTableViewCell to be easily reused, with built-in maximum duration validation and a nib
* Allows CarbStore.defaultAbsorptionTimes to be modified, and resets queries if necessary

Make default absorption times variable on CarbStore

---

CarbKit/CarbMath.swift
CarbKit/UI/CarbEntryEditViewController.swift
CarbKitTests/CarbMathTests.swift
CarbKitTests/UI/CarbEntryEditViewControllerTests.swift

Also prevent input of 0g carb entries

Handle 0g carb entries without crashing

---

CarbKit/CarbStore.swift
CarbKit/UI/CarbEntryEditViewController.swift
CarbKit/UI/CarbKit.storyboard
GlucoseKit/GlucoseStore.swift
InsulinKit/DoseEntry.swift
InsulinKit/DoseStore.swift
InsulinKit/HKQuantitySample+InsulinKit.swift
InsulinKit/InsulinDeliveryStore.swift
InsulinKit/InsulinMath.swift
InsulinKit/NewPumpEvent.swift
InsulinKit/PumpEvent+CoreDataClass.swift
InsulinKit/PumpEventType.swift
InsulinKit/UI/Base.lproj/InsulinKit.storyboard
InsulinKitTests/Fixtures/doses_overlay_basal_profile_output.json
InsulinKitTests/Fixtures/reconcile_history_input.json
InsulinKitTests/Fixtures/reconcile_history_output.json
InsulinKitTests/InsulinMathTests.swift
LoopKit.xcodeproj/project.pbxproj
LoopKit/DailyValueSchedule.swift
LoopKit/GlucoseRangeSchedule.swift
LoopKit/HealthKitSampleStore.swift
LoopKit/UI/CommandResponseViewController.swift
LoopKit/UI/GlucoseRangeTableViewCell.xib
LoopKit/UI/RepeatingScheduleValueTableViewCell.xib
LoopKit/UI/TextFieldTableViewCell.xib
LoopKitTests/BasalRateScheduleTests.swift

* Storing Insulin Delivery data in HealthKit. 
* Providing stable ordering for doses that share a date value
* Tweaks to schedule types (to return both start and end date for an entry) 
* Text size fixes

Insulin in HK, and ordering

---

InsulinKit/DoseStore.swift
InsulinKit/InsulinMath.swift
InsulinKitTests/InsulinMathTests.swift
LoopKit.xcodeproj/xcshareddata/xcschemes/CarbKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/GlucoseKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/InsulinKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit Example.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit.xcscheme
LoopKit/UI/CommandResponseViewController.swift

Add a safety heuristic to determine when to remove pre-reported pending doses
Fix landscape safe-area margins in CommandResponseViewController

Add a safety heuristic

---

CarbKit/es.lproj/CarbKit.strings
CarbKit/es.lproj/InfoPlist.strings
CarbKit/es.lproj/Localizable.strings
GlucoseKit/es.lproj/InfoPlist.strings
GlucoseKit/es.lproj/Localizable.strings
GlucoseKitTests/es.lproj/InfoPlist.strings
GlucoseKitTests/es.lproj/Localizable.strings
InsulinKit/UI/es.lproj/InsulinKit.strings
InsulinKit/es.lproj/InfoPlist.strings
InsulinKit/es.lproj/InsulinKit.strings
InsulinKit/es.lproj/Localizable.strings
LoopKit Example/es.lproj/InfoPlist.strings
LoopKit Example/es.lproj/LaunchScreen.strings
LoopKit Example/es.lproj/Localizable.strings
LoopKit Example/es.lproj/Main.strings
LoopKit.xcodeproj/project.pbxproj
LoopKit/es.lproj/InfoPlist.strings
LoopKit/es.lproj/Localizable.strings
LoopKit/es.lproj/LoopKit.strings

spanish translation

---

.travis.yml
LoopKit.xcodeproj/project.pbxproj
LoopKit.xcodeproj/xcshareddata/xcschemes/CarbKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/GlucoseKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/InsulinKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit Example.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit.xcscheme

Updates travis to use Xcode 9.2, and add static analyzer check for localizability.

Updates travis to use Xcode 9.2

---

CarbKit/CarbStore.swift
GlucoseKit/GlucoseMath.swift
GlucoseKit/GlucoseStore.swift
GlucoseKitTests/GlucoseMathTests.swift
InsulinKit/DoseStore.swift
InsulinKit/InsulinDeliveryStore.swift
LoopKit/HealthKitSampleStore.swift

* Refactors GlucoseKit
* Adds historical insulin counteraction effect computation
* Removes nullable initializer pattern for HealthKitSampleStore

GlucoseKit2

---

LoopKit.xcodeproj/project.pbxproj
LoopKit/CarbKit/CarbStore.swift
LoopKit/DailyQuantitySchedule.swift
LoopKit/DailyValueSchedule.swift
LoopKit/GlucoseKit/GlucoseStore.swift
LoopKit/GlucoseRangeSchedule.swift
LoopKit/InsulinKit/DoseStore.swift
LoopKit/InsulinKit/PersistedPumpEvent.swift
LoopKit/Locked.swift
LoopKit/SampleValue.swift
LoopKitUI/InsulinKit/InsulinDeliveryTableViewController.swift

* Adding locks to *Store properties being accessed across threads
* Removing DoseStore's unnecessary ReadyState enum
* Adding Equatable support for more config types

Cleanup TODOs

---

.gitignore
Extensions/NSData.swift
LoopKit Example/Managers/DeviceDataManager.swift
LoopKit Example/MasterViewController.swift
LoopKit/CarbKit/CarbStore.swift
LoopKit/GlucoseKit/GlucoseStore.swift
LoopKit/HealthKitSampleStore.swift
LoopKit/InsulinKit/DoseEntry.swift
LoopKit/InsulinKit/DoseStore.swift
LoopKit/InsulinKit/HKQuantitySample+InsulinKit.swift
LoopKit/InsulinKit/InsulinDeliveryStore.swift
LoopKit/InsulinKit/InsulinMath.swift
LoopKit/InsulinKit/PersistedPumpEvent.swift
LoopKit/InsulinKit/PumpEvent+CoreDataClass.swift
LoopKit/Locked.swift
LoopKit/Persistence/PersistenceController.swift
LoopKitTests/DoseStoreTests.swift
LoopKitTests/InsulinMathTests.swift
LoopKitUI/CarbKit/CarbEntryTableViewController.swift
LoopKitUI/CommandResponseViewController.swift
LoopKitUI/DailyValueScheduleTableViewController.swift
LoopKitUI/InsulinKit/InsulinDeliveryTableViewController.swift

– Allow extension clients to disable observation queries
– Improved diagnostic logger sharing: supports attachments with a filename
– Fix retain cycles

Improvements in extension support, logging

---

LoopKit.xcodeproj/project.pbxproj
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit Example.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKitUI.xcscheme
LoopKit/InsulinKit/DoseStore.swift
LoopKitUI/SingleValueScheduleTableViewController.swift

saving pump events to HealthKit before resetting

Allow for specifying DoseStore query limit,

---

LoopKit/nb.lproj/Localizable.strings
LoopKit/nl.lproj/Localizable.strings
LoopKit/zh-Hans.lproj/Localizable.strings
LoopKitUI/nb.lproj/CarbKit.strings
LoopKitUI/nb.lproj/InsulinKit.strings
LoopKitUI/nb.lproj/Localizable.strings
LoopKitUI/nl.lproj/Localizable.strings
LoopKitUI/zh-Hans.lproj/CarbKit.strings
LoopKitUI/zh-Hans.lproj/InsulinKit.strings
LoopKitUI/zh-Hans.lproj/Localizable.strings

Last touchups for LoopKit translations

Small translation corrections

---

Common/LocalizedString.swift
LoopKit/CarbKit/CarbStore.swift
LoopKit/CarbKit/NewCarbEntry.swift
LoopKit/GlucoseEffect.swift
LoopKit/GlucoseKit/GlucoseStore.swift
LoopKit/GlucoseKit/NewGlucoseSample.swift
LoopKit/GlucoseRangeSchedule.swift
LoopKit/InsulinKit/DoseStore.swift
LoopKit/InsulinKit/HKQuantitySample+InsulinKit.swift
LoopKit/InsulinKit/InsulinDeliveryStore.swift
LoopKitUI/Base.lproj/Localizable.strings
LoopKitUI/View Controllers/AuthenticationViewController.swift
LoopKitUI/de.lproj/Localizable.strings
LoopKitUI/es.lproj/Localizable.strings
LoopKitUI/fr.lproj/Localizable.strings
LoopKitUI/it.lproj/Localizable.strings
LoopKitUI/nb.lproj/Localizable.strings
LoopKitUI/nl.lproj/Localizable.strings
LoopKitUI/pl.lproj/Localizable.strings
LoopKitUI/ru.lproj/Localizable.strings
LoopKitUI/zh-Hans.lproj/Localizable.strings

* Allow specifying the sync version
* Leveraging auto-synthesized equality
* Accessors for target range quantities

Improvements to support Watch charts

---

Extensions/UUID.swift
LoopKit.xcodeproj/project.pbxproj
LoopKit/HealthKitSampleStore.swift
LoopKit/InsulinKit/DoseStore.swift
LoopKit/InsulinKit/InsulinDeliveryStore.swift
LoopKitTests/DoseStoreTests.swift
LoopKitTests/Extensions/HKHealthStoreMock.swift
LoopKitTests/InsulinMathTests.swift
LoopKitTests/Persistence/PersistenceControllerTestCase.swift

Reproduces and fixes the following: 
* https://github.com/LoopKit/Loop/issues/852
* https://github.com/LoopKit/Loop/issues/853

HealthKit Sync Fix

---

LoopKit/GlucoseRangeSchedule.swift

This fixes a bug where users whose graphs are broken when their target range unit doesn't match the HealthKit preferred unit.

Adjust GlucoseRangeSchedule API to improve unit hygiene

---

LoopKit.xcodeproj/project.pbxproj
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit Example.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKitUI.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/LoopTestingKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/MockKit.xcscheme
LoopKit.xcodeproj/xcshareddata/xcschemes/MockKitUI.xcscheme
LoopKit/BasalRateSchedule.swift
LoopKit/CarbKit/CarbStore.swift
LoopKit/CarbKit/StoredCarbEntry.swift
LoopKit/DailyQuantitySchedule.swift
LoopKit/GlucoseKit/StoredGlucoseSample.swift
LoopKit/InsulinKit/DoseStore.swift
LoopKitUI/Views/ReservoirVolumeHUDView.swift
LoopKitUI/Views/ReservoirVolumeHUDView.xib

And clean up some some Swift warnings

Fix low-reservoir HUD text color

---

LoopKitUI/CarbKit/CarbEntryValidationNavigationDelegate.swift
LoopKitUI/UIAlertController.swift

Fixes https://github.com/LoopKit/Loop/issues/946

Add missing ok button on validation warnings

---

README.md

Replace the gitter badge on the README with a zulipchat badge.

Replace gitter with zulipchat

---

LoopKit/DailyQuantitySchedule+Override.swift
LoopKit/GlucoseRangeSchedule.swift
LoopKit/TemporaryScheduleOverrideSettings.swift

Fixes https://github.com/LoopKit/Loop/issues/1062

Overrides target ranges

---

LoopKitUI/View Controllers/GlucoseRangeScheduleTableViewController.swift

Fixes https://github.com/LoopKit/Loop/issues/1060

Exit edit mode when only one correction range left

---

LoopKit.xcodeproj/project.pbxproj
LoopKit/InsulinKit/CachedInsulinDeliveryObject+CoreDataClass.swift
LoopKit/InsulinKit/CachedInsulinDeliveryObject+CoreDataProperties.swift
LoopKit/InsulinKit/DoseEntry.swift
LoopKit/InsulinKit/DoseStore.swift
LoopKit/InsulinKit/HKQuantitySample+InsulinKit.swift
LoopKit/LoopPlugin.swift
LoopKit/Persistence/Model.xcdatamodeld/Model.xcdatamodel/contents
LoopKitUI/LoopUIPlugin.swift
MockKit/MockPumpManagerState.swift

Support for Loop Plugins, and updates from Tidepool reviews.

Tidepool sync

---

LoopKit/InsulinKit/DoseStore.swift

Fixes https://github.com/LoopKit/Loop/issues/1133

Fix bug in updating pumpEventQueryAfterDate.
